[package]
name = "mazegen-rs"
version = "0.1.0"
authors = ["CianLR <cian.ruane1@gmail.com>"]
licence = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
clap = "2.33.0"
